spring:
  application:
    name: order
  cloud:
    stream:
      binders:
        myinput:
          destination: myStreamExchange #指定输入通道对应的主题名
        myOutput:
          destination: myStreamExchange
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 108512
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#    format-sql: true
#    use-sql-comments: true
#放到客户端
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
env:
  dev111111111
