spring:
  application:
    name: order
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG
      profile: dev
    stream:
      bindings:
        myInput:
          destination: myStreamExchange #指定输入通道对应的主题名
          group: orderGroup
        myOutput:
          destination: myStreamExchange
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 108512
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#    format-sql: true
#    use-sql-comments: true
  rabbitmq:
    host: 192.168.43.9
    port: 5672
    username: guest
    password: guest
evn:
  dev
