spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 108512
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
      host: 192.168.1.17
      port: 5672
      username: guest
      password: guest
  jpa:
    show-sql: true
#    format-sql: true
#    use-sql-comments: true
